enyo.depends(
  "rivets.js",
	"titledmenu.js",
  "titledmenu.css",
	"chatbox.js",
  "chatbox.css",
  "views",
  "module_container.js",
  "navigator.js",
  "flexbox_arranger.js",
  "preliminaries.js"
);
